=== plural/netrunner-cards-json/schema/v2/cards_translation_schema.json
{
  "$id": "https://github.com/netrunnerdb/netrunner-cards-json/blob/master/schema/v2/cards_translation_schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "additionalProperties": false,
  "properties": {
    "faces": {
      "items": {
        "additionalProperties": false,
        "properties": {
          "text": {
            "oneOf": [{ "minLength": 1, "type": "string" }, { "type": "null" }]
          },
          "title": {
            "oneOf": [{ "minLength": 1, "type": "string" }, { "type": "null" }]
          }
        },
        "required": ["title"],
        "type": "object"
      },
      "type": "array"
    },
    "id": { "minLength": 1, "type": "string" },
    "text": {
      "oneOf": [{ "minLength": 1, "type": "string" }, { "type": "null" }]
    },
    "title": {
      "oneOf": [{ "minLength": 1, "type": "string" }, { "type": "null" }]
    }
  },
  "required": ["id", "title"],
  "type": "object"
}

=== plural/netrunner-cards-json/v2/translations/de/cards/sync_everything_everywhere.json
{
  "faces": [
    {
      "text": "[click] Drehe diese Identität um.\nDu zahlst 2[credit] weniger, wenn du einen [click] ausgibst, um eine Ressource zu zerstören (nicht durch die Fähigkeit einer Karte).",
      "title": null
    }
  ],
  "id": "sync_everything_everywhere",
  "text": "[click]: Drehe diese Identität um.\nDer Runner zahlt 1[credit] mehr, wenn er einen [click] ausgibt, um eine Markierung zu entfernen (nicht durch die Fähigkeit einer Karte).",
  "title": "SYNC: Alles. Überall."
}
